# Generated by Django 4.2.9 on 2024-01-20 16:53

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250, validators=[catalog.models.validate_even], verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default='apu-upal-i-uronil-edu.jpg', null=True, upload_to='product/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, validators=[catalog.models.validate_even], verbose_name='Название товара'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=50, verbose_name='Название версии')),
                ('is_active_version', models.BooleanField(default=False, verbose_name='Активная ли версия')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Название продукта')),
            ],
        ),
    ]
