# Generated by Django 4.2 on 2024-01-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_user_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='proprietor',
        ),
    ]
