# Generated by Django 4.2 on 2024-01-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_proprietor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'permissions': [('set_published_status', 'Can publish product'), ('change_description', 'Can change description'), ('change_category', 'Can change category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='published_status',
            field=models.BooleanField(default=False, verbose_name='Было опубликовано'),
        ),
    ]
